name = "SwagerSMP"
author = "Niki"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "223f9d0d9cb88576a30d95b0cfb9cda33f69de378897f313be4a67033837b111"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
