name = "SwagerSMP"
author = "Niki"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a80856ac11114dbfd13678911a7d2284cacd5e5249a5161c2ccd7c03198faf62"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
