name = "SwagerSMP"
author = "Niki"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af1ee291255bf0b328d4c57352c917f3616a86c09f9585cc5675aaf91fe766a4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
