name = "SwagerSMP"
author = "Niki"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc9ef13573cc83bf4e9d2c16c4fb8eb9424059f454efe8ebe3a6184c74c3eb83"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
