name = "SwagerSMP"
author = "Niki"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1162229788d447759d98aed2bb2e77ceabf6df01760c36970caf37a8132edc81"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
