name = "SwagerSMP"
author = "Niki"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92feaca3aa802b97611b24f700037f842bc1a3a86c4a825ec66ac89760d0fcbe"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
