name = "SwagerSMP"
author = "Lith"
version = "1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aab4daf732c593fb61645e0dbc5848d4b7a1ea7ea9431bce67e3b1ecc42a903"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
