name = "SwagerSMP"
author = "Lith"
version = "1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ebc937104b67818a7d021baae333f64d1b3399e88e1658d6982a48355fee2ea"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
