name = "SwagerSMP"
author = "Lith"
version = "1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a13e59d6378285409a250f45fa2ec9fbec5ef42cf72228166f817dab344fb1e"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
