name = "SwagerSMP"
author = "Gamzee"
version = "v3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87b574447295aaab4895fffc5d150f522a7c55b0df5b9a9d841bd12f745bee8f"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = "1.20"
