name = "SwagerSMP"
author = "Lith"
version = "1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "526e55b9c009b9ebda06d587ead6ddf2f7fde0bdea3a222f6da3bb455f593224"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
