name = "SwagerSMP"
author = "Lith"
version = "1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fecb52ebda6436c32c84cbaab93d99289076f1b7b07d639bb2272da0e4ee6162"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
