name = "SwagerSMP"
author = "Lith"
version = "0.3.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c89bec2c4a03e0acbaadb35d752da33a3e2ea584b7fb4edca3128756d131eb54"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
