name = "SwagerSMP"
author = "Gamzee"
version = "v3.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e4bdbdb53c219c7e206d4e00f17d1b27e7051a0cb965ba62aae440a7fc6608b"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = "1.20"
