name = "SwagerSMP"
author = "Lith"
version = "0.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93dcc9227957973f176a72a53207fa65ce749b0d3d6cca710d39db6b4f5f84c7"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
