name = "SwagerSMP"
author = "Lith"
version = "1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8c235d793f798b81ec65ae65a1692a6a4b5f044d8bd09328a103c32e68e29f0"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
