name = "SwagerSMP"
author = "Gamzee"
version = "3.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c17ad5131e8fdfc3706e6fc08783f0cd94ee0930b27666c951a46f875923bb8a"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = "1.20"
