name = "SwagerSMP"
author = "Lith"
version = "1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66ef32f2a435036af39e037be8df110c1ec6dc2b8ebedba6e52fad2709fefc5a"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
