name = "SwagerSMP"
author = "Lith"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "420494fd345b4b77faf6ca72f79a8683c02f35ee447e4f9c5dfc562722574db6"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19"]
