name = "SwagerSMP"
author = "Niki"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e644f30113aa698c16b903150610c7ec21602e7c14148dfbef226fc46b247025"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
