name = "SwagerSMP"
author = "Lith"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1c6cc31ad1e3790fe7298126549de6fe0885d1f8e3c85158f301515c5f29bc4"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
