name = "SwagerSMP"
author = "Lith"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79b12a62170a8d0785cd0b406af4fa0b5c59e04f2c92adf34d0390c6da12fa96"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
