name = "SwagerSMP"
author = "Lith"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ef464d352f09dbb0b5281f5e6cad6d384d068d5162d345046e3437155e73b8a"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
