name = "SwagerSMP"
author = "Gamzee"
version = "3.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10ada391fc0fa31f0edf2187b58c39cb9985189242e9b9ec195c1c1ec7e72447"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = "1.20"
