name = "SwagerSMP"
author = "Gamzee"
version = "3.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deb333cc06558c57d9cfcde38832b7b4d387f1792c09a63045ec6d03e497c6a7"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = "1.20"
