name = "SwagerSMP"
author = "Gamzee"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f216cb32b1bfd6cda3fee178d1ab5e4a5d48ec50620b92168df237866028c91"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = "1.20"
