name = "SwagerSMP"
author = "Gamzee"
version = "3.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56760207e956b476304eb5083876517aa780cb9987ba0210b643a54924bd48da"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = "1.20"
