name = "CIT Resewn"
filename = "CITResewn-0.5.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com//data/otVJckYQ/versions/0.5.1/CITResewn-0.5.1.jar"
hash-format = "sha512"
hash = "25ae31aefffdec6f133903177d0ffbfe57d968b3287561d449c18c183b663c2c9143e214e83b9b85dc60bb719a026d96bce2b32a3cd561b84bfefe6c61fd6c99"

[update]
[update.modrinth]
mod-id = "otVJckYQ"
version = "HRyH7tDk"
