name = "Illuminations 🔥"
filename = "illuminations-1.6.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/753/illuminations-1.6.4.jar"
hash-format = "murmur2"
hash = "1139486306"

[update]
[update.curseforge]
file-id = 3432753
project-id = 292908
release-channel = "beta"
