name = "Illuminations 🔥"
filename = "illuminations-1.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3454/742/illuminations-1.7.1.jar"
hash-format = "murmur2"
hash = "3032131610"

[update]
[update.curseforge]
file-id = 3454742
project-id = 292908
release-channel = "beta"
