name = "SwagerSMP"
author = "Gamzee"
version = "2.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b1a16e77cd2d70d7378c01f45e0e41218d4303d4c34a595a8ffada43371bdea"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
